# RENAME FILE TO 'config.yml'
bot:
  token: MTI0MDczMDI0MDA4NzYyNTgzOQ.GnZKaN.dyTxSchRNizfkk9HX4WoCsNUzBcZ3h1YI0h0XE
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
